POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "Important": false,
    "content":"test1"
}
###
GET http://localhost:3001/api/notes/65b502a9a6740d04f4989144

###
GET http://localhost:3001/api/notes/65b502a94a6740d04f4989144


###
GET http://localhost:3001/api/notes

###
PUT  http://localhost:3001/api/notes/65b502a9a6740d04f4989144
content-Type: application/json

{
    "important": false,
    "content":"update"
}